name: CI/CD Pipeline for Database Automation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install MySQL Client
      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client
    
      # Step 3: Create ClimateData Table
      - name: Deploy Initial Schema
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < sql/create_climatedata_table.sql

      # Step 4: Update Schema
      - name: Add Humidity Column
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < sql/add_humidity_column.sql

      # Step 5: Seed Data
      - name: Seed ClimateData Table
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < sql/data_seeding.sql

      # Step 6: Execute Concurrent Queries
      - name: Run Concurrent Queries
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
         python -m pip install --upgrade pip
         python -m pip install pymysql mysql-connector-python
         python scripts/multi_thread_queries.py
